# -*- coding: utf-8 -*-
"""SketchAI_PWAIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XyK0OCfP9cJjjCnObdsETZSzOGR9lOSb

# I. Preparing the Data

### Imports
"""

import os
import glob
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow as tf
import urllib.request

"""### Getting the list of classes"""

if not os.path.isfile('sketchAI_classList.txt'):
    os.system("""wget 'https://raw.githubusercontent.com/pwaic/pwaic.github.io/master/projects/SketchAI/sketchAI_classList.txt'""")

all_classes = []

with open('sketchAI_classList.txt', 'r') as f:
    all_classes = f.readlines()

all_classes = [x.strip('\r\n\t ') for x in all_classes]
print(all_classes)

"""### Download data off Google servers"""

if not os.path.isdir('data'):
    os.mkdir('data')

    base = 'https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/'
    for c in all_classes:
        if os.path.isfile('data/' + c + '.npy'):
            continue
        cls_url = c.replace('_', '%20')
        path = base + cls_url + '.npy'
        print(path)
        urllib.request.urlretrieve(path, 'data/' + c + '.npy')