theme: jekyll-theme-cayman
title: [Plano West Artificial Intelligence Club]
description: [To provide our members the knowledge, skills, and computational resources for success in the up-and-coming field of artificial intelligence]